/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package components;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JProgressBar;

/**
 *
 * @author barasa
 */
public class splash extends javax.swing.JFrame {

    private final pbthread thread;

    /**
     * Creates new form splash
     */
    public splash() {
        initComponents();
        thread=new pbthread(progress);
        thread.start();
    }
    class pbthread extends Thread{
        JProgressBar pbar;
        pbthread(JProgressBar pbar){
            pbar=progress;
            
        }
        public void run(){
            int min=0,max=100;
            progress.setMinimum(min);
            progress.setMaximum(max);
            progress.setValue(0);
            for(int i=min;i<=max;i++){
                lblpercentage.setText(Integer.toString(i)+"%");
                progress.setValue(i);
               if(i<=25){
                    lblsplash.setText("Loading...");
               }
               else if(i<50){
                     lblsplash.setText("please wait");
               }
               else if(i<=75){
                    lblsplash.setText("Initializing components");
               }
               else if(i>75){
                    lblsplash.setText("welcome");
               }
                try {
                    sleep(100);
                } catch (InterruptedException ex) {
                    Logger.getLogger(splash.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlSplash = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        progress = new javax.swing.JProgressBar();
        lblsplash = new javax.swing.JLabel();
        lblpercentage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setBounds(new java.awt.Rectangle(0, 0, 600, 300));
        setName("splash"); // NOI18N
        setUndecorated(true);
        setResizable(false);

        pnlSplash.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back.jpeg"))); // NOI18N
        jLabel1.setIconTextGap(0);

        progress.setBackground(new java.awt.Color(102, 102, 102));
        progress.setName("progress"); // NOI18N

        lblsplash.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        lblsplash.setForeground(new java.awt.Color(255, 255, 255));
        lblsplash.setText("Loading. . .");

        lblpercentage.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        lblpercentage.setForeground(new java.awt.Color(255, 255, 255));
        lblpercentage.setText("%");

        javax.swing.GroupLayout pnlSplashLayout = new javax.swing.GroupLayout(pnlSplash);
        pnlSplash.setLayout(pnlSplashLayout);
        pnlSplashLayout.setHorizontalGroup(
            pnlSplashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 694, Short.MAX_VALUE)
            .addGroup(pnlSplashLayout.createSequentialGroup()
                .addGroup(pnlSplashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlSplashLayout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(progress, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblpercentage))
                    .addGroup(pnlSplashLayout.createSequentialGroup()
                        .addGap(250, 250, 250)
                        .addComponent(lblsplash)))
                .addContainerGap(120, Short.MAX_VALUE))
        );
        pnlSplashLayout.setVerticalGroup(
            pnlSplashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSplashLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(pnlSplashLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSplashLayout.createSequentialGroup()
                        .addComponent(lblsplash)
                        .addGap(18, 18, 18)
                        .addComponent(progress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblpercentage, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlSplash, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlSplash, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(splash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new splash().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblpercentage;
    private javax.swing.JLabel lblsplash;
    private javax.swing.JPanel pnlSplash;
    private javax.swing.JProgressBar progress;
    // End of variables declaration//GEN-END:variables
}
